spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        timeout: 300s # Aumenta o tempo limite de espera (5 minutos)
      chat:
        options:
          model: llama3.1
          num-predict: 12288
          temperature: 0.1
          num-ctx: 16384

  graphql:
    graphiql:
      enabled: true

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.1
      timeout: 300s
