spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        timeout: 60s
        max-retries: 3
      chat:
        options:
          model: llama3 # ou mistral
          num-predict: 4096

  graphql:
    graphiql:
      enabled: true

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3
      timeout: 300s
