spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3 # ou mistral

  graphql:
    graphiql:
      enabled: true

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3
